# -*- encoding: utf-8 -*-

=begin
#MassPay API

#MassPay API

The version of the OpenAPI document: 0.1.4
Contact: support@masspay.io
Generated by: MassPay Inc.
OpenAPI Generator version: 6.5.0
=end

$:.push File.expand_path("../lib", __FILE__)
require "masspay_ruby_sdk/version"

Gem::Specification.new do |s|
  s.name        = "masspay_ruby_sdk"
  s.version     = MassPayRubySdk::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["MassPay Inc."]
  s.email       = ["support@masspay.io"]
  s.homepage    = "https://github.com/masspayio/masspay-ruby-sdk"
  s.summary     = "MassPay Ruby SDK"
  s.description = "MassPay Ruby SDK"
  s.license     = "Apache-2.0"
  s.required_ruby_version = ">= 2.7"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
