=begin
#MassPay API

#MassPay API

The version of the OpenAPI document: 0.1.4
Contact: support@masspay.io
Generated by: MassPay Inc.
OpenAPI Generator version: 6.5.0
=end

require 'cgi'

module MassPayRubySdk
  class TaxApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get List Of Users Annual Balance
    # @param [Hash] opts the optional parameters
    # @option opts [Float] :amount_threshold If specified, only show users whose total balance exceeds the provided amount
    # @option opts [Integer] :tax_year The year for which we would like to obtain tax information for. If none provided, defaults to previous year.
    # @return [Array<TaxYearUserResp>]
    def get_tax_users(opts = {})
      data, _status_code, _headers = get_tax_users_with_http_info(opts)
      data
    end

    # Get List Of Users Annual Balance
    # @param [Hash] opts the optional parameters
    # @option opts [Float] :amount_threshold If specified, only show users whose total balance exceeds the provided amount
    # @option opts [Integer] :tax_year The year for which we would like to obtain tax information for. If none provided, defaults to previous year.
    # @return [Array<(Array<TaxYearUserResp>, Integer, Hash)>] Array<TaxYearUserResp> data, response status code and response headers
    def get_tax_users_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TaxApi.get_tax_users ...'
      end
      # resource path
      local_var_path = '/tax'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'amount_threshold'] = opts[:'amount_threshold'] if !opts[:'amount_threshold'].nil?
      query_params[:'tax_year'] = opts[:'tax_year'] if !opts[:'tax_year'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<TaxYearUserResp>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['AUTHORIZER_NAME']

      new_options = opts.merge(
        :operation => :"TaxApi.get_tax_users",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TaxApi#get_tax_users\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
