=begin
#MassPay API

#MassPay API

The version of the OpenAPI document: 0.1.4
Contact: support@masspay.io
Generated by: MassPay Inc.
OpenAPI Generator version: 6.5.0
=end

# Common files
require 'masspay_ruby_sdk/api_client'
require 'masspay_ruby_sdk/api_error'
require 'masspay_ruby_sdk/version'
require 'masspay_ruby_sdk/configuration'

# Models
require 'masspay_ruby_sdk/models/api_response'
require 'masspay_ruby_sdk/models/attr_txn'
require 'masspay_ruby_sdk/models/attr_value'
require 'masspay_ruby_sdk/models/attr_velocity_request_inner'
require 'masspay_ruby_sdk/models/attrs_requirement'
require 'masspay_ruby_sdk/models/autopay_resp'
require 'masspay_ruby_sdk/models/autopay_rule'
require 'masspay_ruby_sdk/models/available_balance_txn_resp'
require 'masspay_ruby_sdk/models/companies_resp'
require 'masspay_ruby_sdk/models/company'
require 'masspay_ruby_sdk/models/country'
require 'masspay_ruby_sdk/models/distributors_balances200_response_inner'
require 'masspay_ruby_sdk/models/distributors_balances200_response_inner_balances_inner'
require 'masspay_ruby_sdk/models/exception'
require 'masspay_ruby_sdk/models/found_user'
require 'masspay_ruby_sdk/models/generate_invoice200_response'
require 'masspay_ruby_sdk/models/generate_pricing_list_request'
require 'masspay_ruby_sdk/models/get_account_statement200_response'
require 'masspay_ruby_sdk/models/get_transaction_confirmation_details200_response'
require 'masspay_ruby_sdk/models/get_user_agreement200_response'
require 'masspay_ruby_sdk/models/get_user_agreements_names200_response_inner'
require 'masspay_ruby_sdk/models/get_user_user_token_kyc_au10tix200_response'
require 'masspay_ruby_sdk/models/get_user_user_token_kyc_veriiff200_response'
require 'masspay_ruby_sdk/models/get_wallet_card_info200_response'
require 'masspay_ruby_sdk/models/load_txn'
require 'masspay_ruby_sdk/models/load_txn_resp'
require 'masspay_ruby_sdk/models/loads'
require 'masspay_ruby_sdk/models/payout_txn'
require 'masspay_ruby_sdk/models/payout_txn_commit_resp'
require 'masspay_ruby_sdk/models/payout_txn_resp'
require 'masspay_ruby_sdk/models/post_account_api_key200_response'
require 'masspay_ruby_sdk/models/post_account_api_key_request'
require 'masspay_ruby_sdk/models/resend_load_notification200_response'
require 'masspay_ruby_sdk/models/service'
require 'masspay_ruby_sdk/models/service_payers_inner'
require 'masspay_ruby_sdk/models/service_payers_inner_exchange_rate_inner'
require 'masspay_ruby_sdk/models/spend_back_txn'
require 'masspay_ruby_sdk/models/spend_back_txn_resp'
require 'masspay_ruby_sdk/models/spend_backs'
require 'masspay_ruby_sdk/models/stored_user'
require 'masspay_ruby_sdk/models/txn_history_resp'
require 'masspay_ruby_sdk/models/update_user'
require 'masspay_ruby_sdk/models/upload_batch_request'
require 'masspay_ruby_sdk/models/user'
require 'masspay_ruby_sdk/models/wallet_txn_resp'

# APIs
require 'masspay_ruby_sdk/api/account_api'
require 'masspay_ruby_sdk/api/attribute_api'
require 'masspay_ruby_sdk/api/card_api'
require 'masspay_ruby_sdk/api/catalog_api'
require 'masspay_ruby_sdk/api/internal_api'
require 'masspay_ruby_sdk/api/kyc_api'
require 'masspay_ruby_sdk/api/load_api'
require 'masspay_ruby_sdk/api/payout_api'
require 'masspay_ruby_sdk/api/spend_back_api'
require 'masspay_ruby_sdk/api/user_api'
require 'masspay_ruby_sdk/api/wallet_api'

module MassPayRubySdk
  class << self
    # Customize default settings for the SDK using block.
    #   MassPayRubySdk.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
